### PR TITLE
Feature/nestjs cli menu

### PR DESCRIPTION
**Pull request by dinbtechit**
Feature #213 

1. Now we can right click anywhere in the project to invoke nest cli 

image

2. Select a type to generate
image

3. provide a filename and options, click ok to generate
image

4. Generated using Nest intellij Plugin
image

### CODE REVIEW

**Comment by dinbtechit** [comment]
@nekofar - Hopefully no more changes and its ready for review now.

**Some notes for future improvements:**
1. Identify if it is worth in moving the label texts to the message bundle. If so, we might want to consider refactoring that.
2. Unit Tests / E2E Test case to cover all scenarios. (At the moment, I haven't explored much with unit testing with intellij plugins.)

**Comment by dinbtechit** [comment]
Here are a few more updates:

- handling some edge cases (for example when there are unwanted spaces in the parameters field)
- Now it will try to find the closest module and add automatically update it.
-  UX/UI to show the module path and hides the generated path if it is empty

https://github.com/KartanHQ/intellij-nestjs/assets/17984781/d4ef08fb-c655-4b73-902e-669d5115f78e

**Comment by dinbtechit** [comment]
@nekofar  - Hi Mate! Hope you doing great. Just thought I would just follow up on this PR to see if you have any concerns with the code or something. Cheers!

**Comment by nekofar** [comment]
> @nekofar - Hi Mate! Hope you doing great. Just thought I would just follow up on this PR to see if you have any concerns with the code or something. Cheers!

Hey there! Apologies for the delay in reviewing your work. My bandwidth has been a bit limited lately, but I'm making it a priority to get to it soon. I just need to make a few changes to the repository before we can merge it. Thanks for your patience! 💚

**Comment by dinbtechit** [comment]
@nekofar  - Oh man. I totally hear you. I was in the same boat a few months ago. Please let me know if you would like me to create this as a separate plugin if it is too much for you to take on at the moment.  I also have plans to enhance IntelliSense and generate automated test cases in the future. I was hoping to do some more PRs for them. But I dont want to bog you down with too many requests. Cheers!

**Pull request closed without merging**
